"""Global variables."""

# RiskFormer

RISKNET_MIN_TIME_EMBED_PERIOD_IN_DAYS = 10
RISKNET_MAX_TIME_EMBED_PERIOD_IN_DAYS = 120 * 365
RISKNET_MIN_FOLLOWUP_YEARS_IF_NEGATIVE = 1
RISKNET_MIN_PRE_OUTCOME_DAYS_IF_POSITIVE = 30
RISKNET_MIN_EVENTS_PER_SEQUENCE = 50
RISKNET_NUM_TRAJECTORIES_PER_PATIENT = 5
RISKNET_MONTH_ENDPOINTS = [3, 6, 12, 24, 36]
