defaults:
  - _self_
  - data: default
  - model: default
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  run:
    dir: ./data/outputs/run/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: true
  sweep:
    dir: ./data/outputs/multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  sweeper:
    sampler:
      seed: 123
    direction: maximize
    study_name: risknet
    storage: null
    n_trials: 10
    n_jobs: 1
    params:
      model.learning_rate: 0.00027
      model.num_heads: choice(6)
      model.num_blocks: choice(4)
      model.max_sequence_length: choice(150, 200, 250)

paths:
  # raw: /Users/sedernet/marth/projects/patient2gene/data/datasets/risknet/DravetBase
  raw: /Users/sedernet/marth/projects/patient2gene/data/datasets/risknet/DravetStatusEpilepticusClaims

preprocess:
  num_negative_samples: 15000 # remove
  num_processes: 10 # remove
  seed: 1771

hyper:
  endpoint: 60
  metric: average_precision
  max_splits: 5
